'use server';

/**
 * @fileOverview A comprehensive AI flow for assisting in novel writing.
 * It can generate new content, continue existing text, rephrase, or enhance based on user instructions.
 *
 * - novelCoWriter - Main function to handle different writing tasks.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const NovelCoWriterInputSchema = z.object({
  task: z
    .enum(['generate', 'continue', 'reword', 'enhance'])
    .describe('The specific writing task to perform.'),
  currentContent: z.string().optional().describe('The existing text from the novel or document.'),
  instruction: z.string().describe('The user\'s prompt or instruction for the AI.'),
});

const NovelCoWriterOutputSchema = z.object({
  generatedText: z.string().describe('The resulting text generated by the AI.'),
});


// Define individual prompts for each task to provide clear, focused instructions.

const generatePrompt = ai.definePrompt({
  name: 'novelGeneratePrompt',
  input: {schema: NovelCoWriterInputSchema},
  output: {schema: NovelCoWriterOutputSchema},
  prompt: `You are an expert novelist and creative writing partner.
A user wants you to write a new piece of text based on their instruction.

User Instruction: {{{instruction}}}

Generate the requested content. Return ONLY the new text.`,
});

const continuePrompt = ai.definePrompt({
  name: 'novelContinuePrompt',
  input: {schema: NovelCoWriterInputSchema},
  output: {schema: NovelCoWriterOutputSchema},
  prompt: `You are an expert novelist and creative writing partner.
Your task is to continue writing from the provided text.
Read the following text and write the next logical section (2-3 paragraphs).
Maintain the style and tone perfectly.

Existing Text:
"""
{{{currentContent}}}
"""

User Instruction: {{{instruction}}}

Return the ORIGINAL text followed by the NEW text seamlessly.`,
});

const rewordPrompt = ai.definePrompt({
  name: 'novelRewordPrompt',
  input: {schema: NovelCoWriterInputSchema},
  output: {schema: NovelCoWriterOutputSchema},
  prompt: `You are an expert editor.
Rewrite the following text to be more professional, concise, and impactful.
Fix any grammatical errors.

Text to Reword:
"""
{{{currentContent}}}
"""

Return ONLY the rewritten text.`,
});

const enhancePrompt = ai.definePrompt({
  name: 'novelEnhancePrompt',
  input: {schema: NovelCoWriterInputSchema},
  output: {schema: NovelCoWriterOutputSchema},
  prompt: `You are an expert editor and wordsmith.
Enhance the following text with more vivid vocabulary, better flow, and a more engaging tone.
Fix any grammar issues.

Text to Enhance:
"""
{{{currentContent}}}
"""

Return ONLY the enhanced text.`,
});

const coWriterFlow = ai.defineFlow(
  {
    name: 'novelCoWriterFlow',
    inputSchema: NovelCoWriterInputSchema,
    outputSchema: NovelCoWriterOutputSchema,
  },
  async input => {
    let result;
    switch (input.task) {
      case 'generate':
        result = await generatePrompt(input);
        break;
      case 'continue':
        result = await continuePrompt(input);
        break;
      case 'reword':
        result = await rewordPrompt(input);
        break;
      case 'enhance':
        result = await enhancePrompt(input);
        break;
      default:
        throw new Error(`Unknown task: ${input.task}`);
    }
    return result.output!;
  }
);

export async function novelCoWriter(input: z.infer<typeof NovelCoWriterInputSchema>): Promise<z.infer<typeof NovelCoWriterOutputSchema>> {
  return coWriterFlow(input);
}
